### ISSUE TITLE
Test coverage verification

### ISSUE THREAD

**Issue by MKazimirski** [NeoTech-Software/Android-Root-Coverage-Plugin#101]
Is there an easy way to verify code coverage results produced by the plugin against a threshold? I want to set up a CI job that will perform this verification and fail if the results are below the threshold. I noticed that JaCoCo provides _jacocoTestCoverageVerification_, but I'm unsure how to integrate it within the context of this plugin.

**Comment by Rolf-Smit** [comment]
This plugin currently only configures `JacocoTasks` to create a coverage reports, it currently does not support configuring `JacocoCoverageVerifications` task.

Gradle by default does create `JacocoCoverageVerifications` but only for modules that have the Java Plugin applied, which is not the case for normal Android projects.

Since both Gradle does not provide the task in case of Android, and this plugin does also not provide it (at this point), you need to manually configure this task. However you can leverage the tasks that this plugin already creates to do the heavy lifting for you (So you don't need to manually configure/collect `executionData`, `sourceDirectories` and `classDirectories` etc.).

And example on how to do this on module/app level (this is very rudimentary):

**app/build.gradle**
```gradle
project.tasks.register('jacocoTestCoverageVerification', JacocoCoverageVerification) {
    it.dependsOn("coverageReport")

    //noinspection ConfigurationAvoidance
    JacocoReportBase baseJacocoTask  = project.tasks.getByName("coverageReport")
    executionData { baseJacocoTask.executionData }

    sourceDirectories.setFrom(baseJacocoTask.sourceDirectories)
    classDirectories.setFrom(baseJacocoTask.classDirectories)

    violationRules {
        rule {
            limit {
                minimum = 1.0
            }
        }
    }
}
```

If you execute this task, Gradle will first run the `app:coverageReport` task, then it will run the configured `JacocoCoverageVerification` and depending if you have 100% coverage or not you may see either succeeded or something like this:

```
Execution failed for task ':app:jacocoTestCoverageVerification'.
> Rule violated for bundle app: instructions covered ratio is 0.9, but expected minimum is 1.0
```

If you want to do the same on root level, then you have to place this code in your root build.gradle file and adjust the `coverageReport` dependent/referenced task to `rootCoverageReport` (in both places).


_I think it may be a good idea to add this functionality directly into this plugin. But I cannot promise anything in the near future, it highly depends on my availability and time._

**Comment by MKazimirski** [comment]
@Rolf-Smit Thank you for the detailed answer
