### ISSUE TITLE
Do we have any sample repo to demonstrate the usage of Android-Root-Coverage-Plugin

### ISSUE THREAD

**Issue by anticafe** [NeoTech-Software/Android-Root-Coverage-Plugin#41]
I think this sample repo should have:
- Multi module
- Multi flavor in main module
- At least 1 pure Java/Kotlin module
- At least 1 Android module (unit test + instrumented test).
- The Android Gradle plugin should be 7.0.0+, Java 11, and Gradle wrapper 7.2+.

**Comment by Rolf-Smit** [comment]
Currently there is no such example. I also wonder if something like that would make sense, since this library is pretty easy to setup: 1. add the dependencies, 2. configure the `rootCoverage` block 3. run one of the generated tasks.

This library does come with an integration test that contains a pure Java module, Android library module and app module with both unit tests and instrumented tests, that could serve as an example: https://github.com/NeoTech-Software/Android-Root-Coverage-Plugin/tree/master/plugin/src/test/test-fixtures/multi-module

**Comment by Rolf-Smit** [comment]
I'm closing this issue as this is not something I intend to add anytime soon (as explained in my previous comment the integration test basically is the example and the configuration of the library should be straight forward).
